-- CREATE DATABASE cybersoft_shop
-- GO

-- use cybersoft_shop

CREATE TABLE SanPham (
	MaSP INT PRIMARY KEY IDENTITY(1,1),
	TenSP NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(255) NULL,
	Gia DECIMAL(18, 2) NOT NULL,
	MaLoaiSP INT NOT NULL
);

CREATE TABLE LoaiSanPham (
	MaLoaiSP INT PRIMARY KEY IDENTITY(1,1),
	TenLoaiSP NVARCHAR(100) NOT NULL
);

CREATE TABLE HoaDon (
	MaHD INT PRIMARY KEY IDENTITY(1,1),
	MaKH INT,
	NgayLap DATETIME NOT NULL,
);

CREATE TABLE KhachHang (
	MaKH INT PRIMARY KEY IDENTITY(1,1),
	DiaChi NVARCHAR(255) NULL,
	Email NVARCHAR(100) NOT NULL,
	Ho nvarchar(50) NOT NULL,
	Ten nvarchar(50) NOT NULL,
	SoDienThoai NVARCHAR(20) NOT NULL
);

--1 - 1
ALTER TABLE SanPham
ADD CONSTRAINT FK_SanPham_LoaiSanPham
FOREIGN KEY (MaLoaiSP) REFERENCES LoaiSanPham(MaLoaiSP);

ALTER TABLE HoaDon
ADD CONSTRAINT FK_HoaDon_KhachHang
FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH);

--1 - N
CREATE TABLE ChiTietHoaDon (
	MaCTHD INT PRIMARY KEY IDENTITY(1,1),
	MaHD INT NOT NULL,
	MaSP INT NOT NULL,
	SoLuong INT NOT NULL,
	Gia DECIMAL(18, 2) NOT NULL
);

ALTER TABLE ChiTietHoaDon
ADD CONSTRAINT FK_ChiTietHoaDon_HoaDon
FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD);

ALTER TABLE ChiTietHoaDon
ADD CONSTRAINT FK_ChiTietHoaDon_SanPham
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP);
